In [1]:
#Requirements
import numpy as np

In [2]:
#A sudoku checker using list comprehension
def sudoku_checker(player_input):
    #player_input is a 9 by 9 array representing a completed sudoku board
    print(player_input)
    full_board_error_count= 0
    sub_grid_error_count = 0
      
    #checks entire grid for row and column errors
    for x in range(9):
        row = player_input[x,:]
        column = player_input[:,x]
        if len(row) != len(set(row)) | len(column) != len(set(column)):
            full_board_error_count += 1
    if full_board_error_count == 0:
        print("No errors detected in 9 x 9 grid columns or rows!")
    else:
        print("A total of {} 9 x 9 grid row or column error(s) detected.".format(full_board_error_count))
        
    #checks 3 x 3 sub grids
    for x in range(0,9,3):
        for y in range(0,9,3):
            sub_grid = player_input[x:x + 3,y:y + 3]
            sub_grid_set = {column for row in sub_grid for column in row}
            if sub_grid.size != len(sub_grid_set):
                sub_grid_error_count += 1
    if sub_grid_error_count == 0:
        print("No errors detected in 3 x 3 sub grids!")
    else:
        print("A total of {} 3 x 3 sub grid error(s) detected.".format(sub_grid_error_count))
            
        
    error_total = full_board_error_count + sub_grid_error_count
    if error_total == 0:
        return "There are no mistakes on your sudoku board! :)"
    else:
        if error_total == 1:
            return "There is one error somewhere on your Sudoku board :("
        else:
            return "There are a total of {} errors on your Sudoku board :(".format(error_total)


In [3]:
#Test cell
random_sudoku_board = np.random.randint(1, 9, size = (9,9))
correct_sudoku_board = np.array([[2, 1, 4, 7, 8, 9, 3, 5, 6],
                                      [7, 9, 5, 1, 6, 3, 8, 4, 2],
                                      [8, 6, 3, 4, 2, 5, 9, 1, 7],
                                      [3, 4, 2, 6, 7, 1, 5, 9, 8],
                                      [1, 5, 9, 8, 3, 2, 6, 7, 4],
                                      [6, 7, 8, 5, 9, 4, 2, 3, 1],
                                      [4, 3, 6, 2, 5, 7, 1, 8, 9],
                                      [5, 2, 1, 9, 4, 8, 7, 6, 3],
                                      [9, 8, 7, 3, 1, 6, 4, 2, 5]])

print(sudoku_checker(correct_sudoku_board), "\n")
print(sudoku_checker(random_sudoku_board))

[[2 1 4 7 8 9 3 5 6]
 [7 9 5 1 6 3 8 4 2]
 [8 6 3 4 2 5 9 1 7]
 [3 4 2 6 7 1 5 9 8]
 [1 5 9 8 3 2 6 7 4]
 [6 7 8 5 9 4 2 3 1]
 [4 3 6 2 5 7 1 8 9]
 [5 2 1 9 4 8 7 6 3]
 [9 8 7 3 1 6 4 2 5]]
No errors detected in 9 x 9 grid columns or rows!
No errors detected in 3 x 3 sub grids!
There are no mistakes on your sudoku board! :) 

[[7 1 1 3 5 3 6 1 8]
 [7 5 5 8 7 5 8 5 2]
 [2 3 4 1 1 1 3 2 3]
 [5 8 4 5 5 4 8 1 3]
 [6 2 4 5 2 8 5 8 2]
 [5 4 7 3 7 4 1 6 8]
 [5 8 5 7 4 4 1 2 3]
 [4 2 7 6 1 7 4 3 4]
 [2 4 1 8 2 5 4 8 1]]
A total of 9 9 x 9 grid row or column error(s) detected.
A total of 9 3 x 3 sub grid error(s) detected.
There are a total of 18 errors on your Sudoku board :(
