In [77]:
#Requirements
import numpy as np

In [78]:
def sudoku_checker(player_input):
    #player_input is a 9 by 9 array representing a completed sudoku board
    print(player_input)
    key = list(range(1,9))
    full_board_error_count= 0
    sub_grid_error_count = 0
      
    #checks entire grid for row and column errors
    for x in range(9):
        for y in key:
            if (np.count_nonzero(player_input[x,:] == y) != 1) & (np.count_nonzero(player_input[:,x] == y) != 1):
                full_board_error_count += 1
    if full_board_error_count == 0:
        print("No errors detected in 9 x 9 grid columns or rows! :)")
    else:
        print("A total of {} 9 x 9 grid row or column error(s) detected.".format(full_board_error_count))
        
    #checks 3 x 3 sub grids
    for row in range(3):
        for column in range(3):
            if np.count_nonzero(player_input[row:row + 3,column:column + 3]) != 1:
                sub_grid_error_count += 1
    if sub_grid_error_count == 0:
        print("No errors detected in 3 x 3 sub grids! :)")
    else:
        print("A total of {} 3 x 3 sub grid error(s) detected.".format(sub_grid_error_count))
            
        
    if bool(full_board_error_count) == False or bool(sub_grid_error_count) == False:
        return "What you have on your Sudoku board thus far is correct!"
    else:
        return "There's at least one mistake somewhere on your Sudoku board :("


In [79]:
#Test cell
random_test_sudoku_board = np.random.randint(1, 9, size = (9,9))
correct_test_sudoku_board = np.array([[2, 1, 4, 7, 8, 9, 3, 5, 6],
                                 [7, 9, 5, 1, 6, 3, 8, 4, 2],
                                 [8, 6, 3, 4, 2, 5, 9, 1, 7],
                                 [3, 4, 2, 6, 7, 1, 5, 9, 8],
                                 [1, 5, 9, 8, 3, 2, 6, 7, 4],
                                 [6, 7, 8, 5, 9, 4, 2, 3, 1],
                                 [4, 3, 6, 2, 5, 7, 1, 8, 9],
                                 [5, 2, 1, 9, 4, 8, 7, 6, 3],
                                 [9, 8, 7, 3, 1, 6, 4, 2, 5]])

sudoku_checker(correct_test_sudoku_board)
sudoku_checker(random_test_sudoku_board)

[[2 1 4 7 8 9 3 5 6]
 [7 9 5 1 6 3 8 4 2]
 [8 6 3 4 2 5 9 1 7]
 [3 4 2 6 7 1 5 9 8]
 [1 5 9 8 3 2 6 7 4]
 [6 7 8 5 9 4 2 3 1]
 [4 3 6 2 5 7 1 8 9]
 [5 2 1 9 4 8 7 6 3]
 [9 8 7 3 1 6 4 2 5]]
No errors detected in 9 x 9 grid columns or rows! :)
A total of 9 3 x 3 sub grid error(s) detected.
[[8 1 1 8 4 5 1 2 2]
 [4 7 2 8 2 7 1 1 2]
 [5 4 4 2 7 3 1 4 1]
 [4 1 3 8 4 5 3 2 6]
 [6 2 1 4 7 5 3 3 3]
 [1 2 4 2 6 4 6 3 1]
 [1 2 4 8 4 3 4 7 4]
 [5 2 6 2 2 1 3 7 4]
 [4 3 4 6 1 4 5 4 3]]
A total of 27 9 x 9 grid row or column error(s) detected.
A total of 9 3 x 3 sub grid error(s) detected.


"There's at least one mistake somewhere on your Sudoku board :("